* Active BUGS

** BUG An error occurred while installing sass-embedded (1.98.0), and Bundler cannot continue
:PROPERTIES:
:STATUS:   FIXED
:CREATED:  [2026-02-20]
:FIXED:    [2026-03-16]
:SEVERITY: HIGH
:END:

*** Steps to Reproduce
$ jekyll serve
Could not find proper version of jekyll (4.4.1) in any of the sources
Run `bundle install` to install missing gems.
fenix@anka4 ~/EducaMadrid-NC/PROGRAMACION/pythonisas.github.io (main)
$ bundle install 
Bundler 2.3.3 is running, but your lockfile was generated with 2.6.9. Installing Bundler 2.6.9 and restarting using that version.
Fetching gem metadata from https://rubygems.org/..........
Fetching bigdecimal 3.1.1
Fetching csv 3.2.2
Fetching json 2.6.1
Fetching logger 1.5.0
Installing bigdecimal 3.1.1 with native extensions
Installing json 2.6.1 with native extensions
Installing csv 3.2.2
Installing logger 1.5.0
Fetching addressable 2.8.9
Installing addressable 2.8.9
Fetching google-protobuf 4.34.0
Installing google-protobuf 4.34.0 with native extensions
Fetching sass-embedded 1.98.0
Installing sass-embedded 1.98.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass
/home/fenix/.rvm/rubies/ruby-3.1.0/bin/ruby -I/home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0 -rrubygems /home/fenix/.rvm/gems/ruby-3.1.0/gems/rake-13.3.1/exe/rake
RUBYARCHDIR\=/home/fenix/.rvm/gems/ruby-3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.98.0 RUBYLIBDIR\=/home/fenix/.rvm/gems/ruby-3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.98.0
gem install --force --install-dir /home/fenix/.rvm/gems/ruby-3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.98.0/sass/ruby --no-document --ignore-dependencies --platform x86_64-linux-gnu --version 1.98.0 sass-embedded
rake aborted!
NameError: uninitialized constant JSON::Fragment
<internal:/home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass/Rakefile:302:in `package_json'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass/Rakefile:308:in `dart_sass_version'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass/Rakefile:316:in `dart_sass'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass/Rakefile:54:in `rescue in block in <top (required)>'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass/Rakefile:49:in `block in <top (required)>'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass/Rakefile:82:in `block in <top (required)>'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/rake-13.3.1/exe/rake:27:in `<main>'

Caused by:
Gem::UnsatisfiableDependencyError: Unable to resolve dependency: user requested 'sass-embedded (= 1.98.0)'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass/Rakefile:231:in `gem_install'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass/Rakefile:49:in `block in <top (required)>'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0/ext/sass/Rakefile:82:in `block in <top (required)>'
/home/fenix/.rvm/gems/ruby-3.1.0/gems/rake-13.3.1/exe/rake:27:in `<main>'
Tasks: TOP => dart-sass/sass
(See full trace by running task with --trace)
rm -rf /home/fenix/.rvm/gems/ruby-3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.98.0/sass/ruby

rake failed, exit code 1

Gem files will remain installed in /home/fenix/.rvm/gems/ruby-3.1.0/gems/sass-embedded-1.98.0 for inspection.
Results logged to /home/fenix/.rvm/gems/ruby-3.1.0/extensions/x86_64-linux/3.1.0/sass-embedded-1.98.0/gem_make.out

  /home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  /home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/ext/rake_builder.rb:28:in `build'
  /home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
  /home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  /home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  /home/fenix/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/rubygems/installer.rb:847:in `build_extensions'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/rubygems_gem_installer.rb:111:in `build_extensions'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/rubygems_gem_installer.rb:30:in `install'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/source/rubygems.rb:220:in `install'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/installer/gem_installer.rb:55:in `install'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/installer/gem_installer.rb:17:in `install_from_spec'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/installer/parallel_installer.rb:133:in `do_install'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/installer/parallel_installer.rb:124:in `block in worker_pool'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/worker.rb:62:in `apply_func'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/worker.rb:54:in `loop'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/worker.rb:54:in `process_queue'
  /home/fenix/.rvm/gems/ruby-3.1.0/gems/bundler-2.6.9/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing sass-embedded (1.98.0), and Bundler cannot continue.

In Gemfile:
  minima was resolved to 2.5.2, which depends on
    jekyll-feed was resolved to 0.17.0, which depends on
      jekyll was resolved to 4.4.1, which depends on
        jekyll-sass-converter was resolved to 3.1.0, which depends on
          sass-embedded
fenix@anka4 ~/EducaMadrid-NC/PROGRAMACION/pythonisas.github.io (main)
$ 
*** Expected Behavior
 jekyll to serve 

*** Actual Behavior
jekyll server does not serve the site 

*** Investigation Notes
- Root cause: =sass-embedded 1.98.0= uses =JSON::Fragment=, a constant only available in Ruby >= 3.3
- Current Ruby: 3.1.0 (EOL since March 2025)
- Dependency chain: minima → jekyll-feed → jekyll → jekyll-sass-converter 3.x → sass-embedded

*** Fix Applied [2026-03-16]
- Pinned =jekyll-sass-converter ~> 2.0= in Gemfile (uses =sassc= instead of =sass-embedded=)
- Deleted =Gemfile.lock= and ran =bundle install= successfully
- Verified =jekyll serve= returns HTTP 200
- Long-term: upgrade Ruby to 3.3+ via rvm


** BUG markdown content proper formatting ,
:PROPERTIES:
:STATUS:   ACTIVE
:CREATED:  [2026-02-20]
:SEVERITY: [HIGH/MEDIUM/LOW]
:END:

*** Steps to Reproduce
review new poo2.md file, so that Jekyll renders it properly 

*** Expected Behavior
Jekyll renders it properly 

*** Actual Behavior


*** Investigation Notes


*** Potential Fix

