baseURL = "https://pythonisas.github.io/"
title   = "Pythonisas"
languageCode = "es"
timeZone = "Europe/Madrid"
theme = "smol"
canonifyurls = true
# Parameters
[params]
    author = "Pythonisas"
    authorGithub = "https://github.com/pythonisas"
    mainSections = ["posts"]
    Subtitle = "Brujas del teclado. Alquimistas de los bits."
    dateFmt = "02 Jan 2006"

[markup.goldmark.renderer]
  unsafe = true

# Header
[menu]
  [[menu.main]]
    identifier = "inicio"
    name       = "Inicio"
    url        = "/pages/inicio"
    weight     = -200
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = -100
  [[menu.main]]
    identifier = "rss"
    name       = "RSS"
    url        = "/index.xml"
    weight     = 0

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/pythonisas"
        weight = 1
