#+hugo_base_dir: ../
#+hugo_section: posts


* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:END:

** TODO Conducting Cybersecurity Investigations in Emacs
CLOSED: [2023-11-05 Sun 20:24]
:PROPERTIES:
:EXPORT_FILE_NAME: conducting-cybersecurity-investigations-in-emacs
:EXPORT_HUGO_PUBLISHDATE: 2023-11-05
:EXPORT_HUGO_DRAFT: true
:END:
*** DONE Emacs + Orgmode + Cybersecurity = Winning
I work as a Cybersecurity Analyst and I use Emacs as my primary note taking application. Naturally I have developed some techniques and writing practices around my work and the use of Emacs aids in the process. I think the power of Emacs and Orgmode are a winning combination for the type of work I do. So let me share with you a some of the templates I created that help me in getting work done!
*** The /Investigation/ Template
Recently, I published my [[https://github.com/eduardo-robles/cyber-work-templates][templates]] on Github. Let's take a look at my /Investigations/ template.

**** Creating notes on investigations
#+begin_example
#+TITLE:
#+AUTHOR:
#+EMAIL:

 * Investigations
 * * IN-PROGRESS Investigation#: Suspicious Powershell Command  Date Created: 20230101
:properties:
:export_file_name: 20230101_investigation_suspciouspowershell
:end:
#+end_example
Here I am laying out the main information about this document. I set a title, author, and email address. I also include information about the date it was created and what the status of the to-do item is. In the =properties= drawer, I include an =export_file_name= section, so I can carefully curate my export to HTML or whatever I want.

**** The meat and bones
#+begin_example
 * * * Vendor
Super Duper Cybers Corps.
 *** Title
Suspicious Powershell Command Executed by Finance Department
 *** Assigned:
Eduardo Robles
 *** Contacts
- Cyber Team
- Eduardo Robles
 *** Description
Our IDR logged an a suspicious Powershell command executed from the Finance department.
 *** Questions
1. Was this an intentional execution?
2. What is the purpose of the Powershell command?
3. Did anyone verify with I.T department regarding the Powershell command in question?
 *** Solutions [%]
- [ ] Investigate the origin of the Powershell command
- [ ] Speak with employee who's work station is in question and their supervisor
- [ ] Flag the Powershell command as suspicious
 *** Notes
:LOGBOOK:
:END:
 *** Debug/Troubleshooting Logs
:LOGBOOK:
:END:
 *** Email/Chat Logs
:LOGBOOK:

:END:
#+end_example
In this portion, I include as many details as I can about the ongoing investigation. These notes usually end up as a report that I hand into upper management. So I have to be as descriptive as I can be.

I tend to use =org-contacts= in my /Contacts/ section to make it easier to show email address when I export my content to HTML. In the /Solutions/ section I include =org-checkboxes= so I can keep track of work. In my /Notes/, /Debug+Troubleshooting Logs/, and /Email+Chat Logs/ sections I take advantage of =LOGBOOK= to create timestamped notes of events.
*** It's all about writing it down
Alerts are constant in my line of work. So it's easy to get distracted and disorganized with all the noise. Developing a practice of consistently writing out notes is key to finding calm in all the noise. I developed this template after a lot of trial and error. And I am still working on them but for now they work for me. The best part is that they modular. Use what works and add or remove what doesn't.

** TODO Cyber Work Templates by Me!
CLOSED: [2023-10-22 Sun 09:08]
:PROPERTIES:
:EXPORT_FILE_NAME: cyber-work-templates-by-me
:EXPORT_HUGO_PUBLISHDATE: 2023-10-22
:EXPORT_HUGO_DRAFT: true
:END:

*** The obvious approach
I use Emacs + Org-mode for my note-taking workflow as a Cybersecurity Analyst. Emacs is my geeky cred at my job, plus it is genuinely useful. So one day when working on taking some repetitive notes on an incident I had a bright idea. Why don't I just create a few templates that speed up my workflow?
- A demonstration of my workflow for capturing notes on an incident
   #+begin_example
   Incident --> Get Data --> Investigation --> Capture Templates --> Notes
   #+end_example
*** Expanding the approach
Once I became comfortable with the approach of my capture templates, I expanded them to use the full power of Emacs and Org-mode! I began integrating Org-babel into my workflow. I use a Window 10 PC for my day job and I have WSL2 for all my Linux needs. Furthermore, I can call WSL from a regular shell (by default it calls the Windows Command Prompt) in Emacs. Org-babel does the work of putting the results in my notes. If this sounds familiar to you ~#Emacs~ nerds, well it's the concept of [[https://howardism.org/Technical/Emacs/literate-devops.html][Literate Devops]] by Howard Abrams. I as many others was inspired by the work of Howard Abrams and decided to incorporate their ideas into my workflow. It's a little weird to use these tools in a Windows environment, but hey it works ¯\_(ツ)_/¯.

#+begin_quote
Here I am explaining one of my weird workflows.

https://emacs.ch/@tacosandlinux/111108755456994431
#+end_quote

*** The templates and beyond
So I put up my templates on [[https://github.com/eduardo-robles/cyber-work-templates][Github]] and licensed them under ~CC BY-SA 4.0~. I will continue working on them and updating them as needed. At the time of writing this blog post, I move my note-taking workflow to [[https://www.orgroam.com/][Org Roam]] and I will be tweaking the templates to better fit that workflow. But I plan on creating a different set of templates, I do change them.

I mentioned Literate Devops earlier and while my workflow isn't "Devops" but it is "Literate". It's more like /Literate Pentesting/ which is very useful for me. I am not the first one to try this idea for Pentesting. [[https://github.com/mttaggart][Michael Taggart]] and [[https://github.com/HuskyHacks][@HuskyHacks]] have the really cool project [[https://github.com/mttaggart/blue-jupyter][Blue Jupyter]]. They take the Jupyter Notebooks and apply them to Blue Team work.

So check out and fork my templates on github! Happy Hacking!

https://github.com/eduardo-robles/cyber-work-templates

** TODO Certs for Homelab
CLOSED: [2023-04-27 Thu 18:00]
:PROPERTIES:
:EXPORT_FILE_NAME: certs-for-homelab
:EXPORT_HUGO_PUBLISHDATE: 2023-04-27
:EXPORT_HUGO_DRAFT: true
:END:
I recently had the opportunity to add an ~ssl~ certificate in my homelab environment. It was really easy and only took one command in Linux. Once I created my ~ssl~ certificate all I had to do was upload it to NGINX Proxy Manager and have it serve it to my proxied sites.

You can use any other proxy manager such as Caddy but I had NGINX Proxy Manager in my homelab environment. Be sure to upload both the ~.crt~ and ~.key~ files.

Let's examine what the following commands does.

#+BEGIN_SRC bash
openssl req -newkey rsa:4096 -x509 -sha256 365 -nodes -out homessl.crt -keyout homessl.key
#+END_SRC

First ~openssl req -newkey rsa:4096 -x509 -sha256 365~ stating that we want openssl to create a new certificate using ~rsa 4096~ with type of ~x509~ a hash of ~sha 256~ for ~365~ days.

Then ~-nodes -out homessl.crt -keyout homessl.key~ is telling openssl that we want the cert file and a key file.

Once you run this command you should have 2 files on your system. In this example they would be ~homessl.crt~ and ~homessl.key~. Those 2 files you simply upload to your proxy manager or cert authority of choice and you will have valid self-signed openssl certificates. If you are curious to learn more about OpenSSL you can always check out the manpages online at https://www.openssl.org/docs/man3.0/man7/crypto.html.

** TODO Using a Reverse Proxy and Pi-Hole
CLOSED: [2022-10-20 Thu 06:37]
:PROPERTIES:
:EXPORT_FILE_NAME: reverse-proxy-and-pihole
:EXPORT_HUGO_PUBLISHDATE: 2022-10-20
:EXPORT_HUGO_DRAFT: true
:END:
I recently setup NGINX Proxy Manager to help manage all of my self-hosted services. How did I do this? I installed NGINX Proxy Manager in a LXC container in my Proxmox server. I then configured several of my services to route to their respective IP addresses and ports. In NGINX Proxy Manager you can assign local domain name to your services. I chose to go with something simple like =example.home=. Once I finished configuring NGINX Proxy Manager I moved over to configure my Pi-Hole server. I run the latest version of Pi-Hole on a Raspberry Pi 4 B+ which works fantastic. In my Pi-Hole I simply added some new DNS record to match my NGINX configurations.

*** Example of my Pi-Hole DNSMASQ Settings

**** A Record: =proxy.homeserver.home= --> =10.0.11.1000=

**** CNAME Record: =proxmox.home= --> =proxy.homeserver.home=

**** CNAME Record: =plex.home= --> =proxy.homeserver.home=

Since I am using Pi-Hole as my DNS server I need to have the custom domains I setup in NPM (NGINX Proxy Manager) to route traffic correctly. I start by setting up an =A Record= of my NPM custom domain to point to the IP of NPM. Doing so will ensure that all traffic that goes to that IP gets routed only to NPM. Any traffic that NPM then reads it can then route to the proper service. Next, I make CNAME  records of all the services I have running with custom domains. Now here I state that any request to my custom domains be routed to the A record of my NPM. The reason I need to do this is because traffic needs to route NPM so NPM can decide how to serve up the service. That after all is the job of a reverse proxy.

And that's it! Once I have all settings in place I can start using my custom domains on my local LAN. This make so much easier to reach my local services instead of memorizing IP addresses. In the future I look forward to setting up some local SSL certificates to secure my local custom domains with SSL.

** TODO Starting a Homelab with Proxmox
:PROPERTIES:
:EXPORT_FILE_NAME: starting-homelab-proxmox
:EXPORT_HUGO_PUBLISHDATE: 2021-07-04
:EXPORT_HUGO_DRAFT: true
:END:
  The Beginning

So if you hadn't heard of the idea of a "homelab", let me give you the quick run down of what is a "homelab". Basically, a homelab is a collection of technologies (hardware and software) that you install, maintain, and configure in your home. Imagine a datacenter in your home or an electronics lab can also be a homelab. At the heart of the homelab movement is the idea of tinkering and learning.

Inspired by the idea of tinkering and learning I went down the path of building my own homelab. Luckily you don't need a lot to started, older hardware can be a great start for beginners. That's were my trusty old Dell Xeon workstation comes in. I was gifted this Dell Xeon workstation from a former client and I used it as a Ubuntu workstation for many years. It is a great machine and despite its age work like a champ. Unfortunately, it's loud and does not meet the "Wife Approval Factor". To keep my wife and to start a new journey for this Dell, I decided to turn into my Proxmox machine!
The Homelab

Now what is Proxmox?

Proxmox is Type 1 Hypervisor that you can install on your own hardware. It allows you to run multiple Virtual Machines and Linux Containers (LXC). This is how I'm going be able to run various technologies in my home. Proxmox is a great hypervisor, it's user friendly and built on a stable Debian base. I'm quite comfortable on Debian based distros, so going with Proxmox was a no-brainer.
The Services

In order to stay a bit organized I made a list of services/technologies I wanted to run on my homelab. Below are the services I currently have installed.
#+BEGIN_QUOTE
    File server
    Plex server
    Syncthing
    Git server
    Home Assistant
    GNS3 VM
#+END_QUOTE

** TODO SSH Port Forward a VNC Connection
:PROPERTIES:
:EXPORT_FILE_NAME: ssh-port-forward-vnc
:EXPORT_HUGO_PUBLISHDATE: 2020-02-05
:EXPORT_HUGO_DRAFT: true
:END:
  Recently I wanted to access a Virtual Machine I had created on my desktop from my laptop. I had access to the desktop via SSH but I wanted access to the virtual machine. To make things more interesting I wanted to access the VM(virtual machine) via a graphical interface.

So I figured out that I could use SSH to "port forward" the VNC connection from the desktop to my laptop. It's actually very easy and only requires a few basic SSH commands. All you have to know before hand is the IP addresses and ports of the application and what port you want to connect to locally.

Definitions:

pc-1: Is the computer you are connecting from, in this case the laptop.

pc-2: Is the computer you are connecting to, in this case the desktop with the VM.

So I use KVM to run the VM, so to get the VNC port from the running VM do the following.

#+BEGIN_SRC sh
sudo virsh dumpxml NameOfVM | grep vnc
#+END_SRC
You should see an output like this one.

#+BEGIN_QUOTE
<graphics type='vnc' port='5901' autoport='yes' listen='127.0.0.1'>
#+END_QUOTE

This tells you that KVM is running vnc on port 5901 on address 127.0.0.1 (localhost) for this virtual machine. Now it's time to connect to the virtual machine from pc-1.

In pc-1 run the following command to create an SSH tunnel that port forward the VNC connection.
#+BEGIN_SRC sh
ssh user@pc-2 -L 5901:127.0.0.1:5901
#+END_SRC
What is is command doing?
#+BEGIN_QUOTE
    ssh user@pc-2 is establishing the SSH connection to pc-2 with the user "user". In your case, the user and IP address might be different e.g batman@10.10.0.1.
    -L 5901:127.0.0.1:5901 is telling SSH agent to create a tunnel using local port 5901 and bind it to the remote machine address 127.0.0.1 on port 5901. The address on the remote machine might be different so that's why we ran the virsh command to find it.
#+END_QUOTE

Now that the SSH tunnel is established connect to the VM via VNC. You can use any remote viewer software like Remmina, TightVNC, or even Remote Viewer (part of Virtual Machine Viewer). Simply connect with the following parameters.
#+BEGIN_SRC sh
vnc://localhost:5901
#+END_SRC
And the VNC connection should open up and start working. You can do everything you could locally via a remote VNC connection. Once you are done simply close the VNC connection and exit the SSH session.

In this tutorial I showed how to this in KVM but VirtualBox and VMware have their own methods of doing this. Simply search for "headless" virtual machine for each to find out how to accomplish the same procedure.

Congrats, you are now running a headless VM with a secure connection. SSH is cool tool that can do alot and if you combine it with other tools you can accomplish even more.

** TODO Fixing Grub on a Dual Boot
:PROPERTIES:
:EXPORT_FILE_NAME: fix-grub-dual-boot
:EXPORT_HUGO_PUBLISHDATE: 2019-12-18
:EXPORT_HUGO_DRAFT: true
:END:
  I recently decided to move my Ubuntu installation from my laptop to my desktop without having to reinstall. So basically all I wanted to do is move the SSD (which had Ubuntu 19.10 installed) in my laptop to my desktop. This process is not hard at all but in my case it was a little more complicated. I wanted to do a dual boot on my desktop computer with 2 different hard drives. One spinning disk hard drive will have a Windows 10 installation while the SSD from my laptop will have Ubuntu 19.10. Again I did not want to do any reinstall of Windows 10 or Ubuntu. So how can you accomplish this? Simple with the command update-grub.



First I removed the SSD in the laptop and installed it in my desktop. I ensured that it was on the first SATA port so it can be the first hard drive the system recognizes. Once installed I booted up the computer and Ubuntu booted up correctly. Ok, so now I knew Ubuntu worked fine on the desktop.

Next, I had to update grub inside of Ubuntu in order to add the Windows 10 disk to my boot order. Grub is actually pretty good at adding additional operating systems to the boot order. So turned off the computer ensured that my drives were in the correct SATA ports. After this step I ran into a small problem, Grub was not updating inside my Ubuntu installation. So I decided to boot into a Linux LiveUSB to help troubleshoot the errors.

Inside the LiveUSB Linux environment I used a chroot environment to reach my Ubuntu  19.10 installation. To do so simply follow these steps.

#+BEGIN_SRC sh
sudo mount /dev/sdaX /mnt

for i in /dev/ /dev/pts /proc /sys /run; do sudo mount -B $i /mnt$i; done

sudo chroot /mnt
#+END_SRC
Once in the chroot environment I ran update-grub and I still got an error. So I decided it would be best to simply reinstall grub. To do so simply run reinstall grub-pc (if you're on a efi system please use grub-efi-amd64). This command worked and prompted me to chose where I wanted to install grub. I chose on the main disk since this is where I wanted to have grub installed. Once that process was done, I rebooted the system and was prompted with a working grub boot screen with both operating systems showing up correctly.

Tip: If you want to customize your Grub boot screen you can do with the app Grub Customizer. Simply install it with sudo apt install grub-customizer. This allows you to add a background to Grub bootscreen, change the boot order, and much more.

** TODO Reset Windows Password with Linux
:PROPERTIES:
:EXPORT_FILE_NAME: reset-windows-password-linux
:EXPORT_HUGO_PUBLISHDATE: 2019-07-15
:EXPORT_HUGO_DRAFT: true
:END:
  Ever needed to reset your Windows password but forgot to make a Windows Reset Password disk? If so, you can easily reset a Windows Users password with a Live Linux USB. Let's see just how easy it is to so.

    If you don't a Live Linux USB go ahead an create one. This tutorial is Ubuntu based so any Ubuntu flavor will work. And you will need a working internet connection to download software.
    Start the computer and boot into the Live Linux environment.
    Once in the Live Linux environment make sure you connect to the internet and open a terminal.
    You will need to install tool called chntpw. So ahead and run the following command to install chntpw apt-get install chntpw
    Once installed you will have to mount the hard drive that has Windows installed. There are many ways of doing this but you can use the File Manager (Nautilus in Ubuntu) to make things easy.
    Once you have the Windows Harddrive mounted go to the following directory /windowsHarddrive/Windows/System32/config/
    Now that you are at the correct directory, right click and chose Open With
    Terminal Here.
    In the terminal simply type the following command to interact with chntpwsudo chntpw SAM
    Now you are editing the Administrator user if you would like to edit another user use this command.sudo chntpw -u USERYOUWANTTOEDIT SAM
    After you've chosen your user it's time to reset their password. Simply type 1 in ther User Edit Menu. And then chose y when prompted to Write hive
    files
    Then to quit type q and this will exit chntpw
    Close the terminal and restart your computer making sure to remove the Live Linux USB.
    You should boot into Windows desktop directly without any login. Be sure to add a new password!

Congratulations you have successfully reset your Windows with Linux! And that's it!
